version: '3'

services:
 src:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "8080"
   ports:
     - "8080:8080"
 db:
   image: postgres:15.4-alpine3.18
   environment:
     POSTGRES_PASSWORD: root123
     POSTGRES_DB: root